"use client";

import {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

import {
  canTransitionPurchase,
  canTransitionQuote,
  canTransitionWorkOrder,
  normalizePurchaseStatus,
  normalizeQuoteStatus,
  normalizeWorkOrderStatus,
  PurchaseStatus,
  QuoteStatus,
  WorkOrderStatus,
} from "@/lib/business-states";
import { catalogRecords, customerRecords, supplierRecords } from "@/lib/mock-data";
import { formatClp, parseClp } from "@/lib/formatters";
import {
  buildConsumptionMovements,
  buildReceiptMovements,
  buildReservationMovements,
  HandoffMovementInput,
  movementSignature,
} from "@/lib/workflow-handoff";

export type QuoteLineSource = "catalogo" | "custom";

export type SharedQuoteLine = {
  id: string;
  source: QuoteLineSource;
  code: string;
  name: string;
  type: string;
  unit: string;
  quantity: number;
  unitPrice: number;
  discountPercent: number;
  notes: string;
  stock: string;
};

export type QuoteDraft = {
  customer: string;
  validityDays: string;
  deliveryWindow: string;
  note: string;
  includeVat: boolean;
  lines: SharedQuoteLine[];
};

export type SavedQuote = {
  id: string;
  number: string;
  customer: string;
  rut: string;
  commune: string;
  paymentTerms: string;
  validUntilLabel: string;
  deliveryWindow: string;
  note: string;
  includeVat: boolean;
  subtotal: number;
  tax: number;
  total: number;
  lines: SharedQuoteLine[];
  status: QuoteStatus;
  createdAt: string;
  workOrderNumber?: string;
};

export type PurchaseSuggestion = {
  id: string;
  item: string;
  sourceCode: string;
  sourceLineId: string;
  requiredQuantity: number;
  availableStock: number;
  shortageQuantity: number;
  suggestedSupplier: string;
  unitCost: number;
  reason: string;
};

export type StoredWorkOrder = {
  id: string;
  number: string;
  quoteNumber: string;
  customer: string;
  area: string;
  responsible: string;
  proof: string;
  dueDate: string;
  requiresInstallation: boolean;
  notes: string;
  stages: string[];
  status: WorkOrderStatus;
  totalLabel: string;
  lines: SharedQuoteLine[];
  purchaseSuggestions: PurchaseSuggestion[];
  createdAt: string;
  purchaseNumber?: string;
  stockReserved?: boolean;
  stockConsumed?: boolean;
};

export type StoredPurchaseLine = {
  id: string;
  item: string;
  quantity: number;
  unitCost: number;
  purpose: string;
};

export type StoredPurchase = {
  id: string;
  number: string;
  supplier: string;
  eta: string;
  status: PurchaseStatus;
  lines: StoredPurchaseLine[];
  subtotal: number;
  vat: number;
  total: number;
  createdAt: string;
  sourceReference: string;
  receivedAt?: string;
};

export type InventoryOperation = "Reserva" | "Entrada" | "Salida" | "Ajuste";

export type StoredInventoryMovement = {
  id: string;
  item: string;
  operation: InventoryOperation;
  quantity: number;
  reference: string;
  createdAt: string;
  autoGenerated?: boolean;
};

type AppStateContextValue = {
  quoteDraft: QuoteDraft;
  savedQuotes: SavedQuote[];
  workOrders: StoredWorkOrder[];
  purchases: StoredPurchase[];
  inventoryMovements: StoredInventoryMovement[];
  quoteDraftTotals: {
    subtotal: number;
    tax: number;
    total: number;
    hasProductionWork: boolean;
    requiresPurchaseReview: boolean;
  };
  liveStats: {
    quotes: number;
    workOrders: number;
    purchases: number;
    inventoryMovements: number;
    quoteValue: number;
    purchaseValue: number;
    approvedQuotes: number;
    openPurchases: number;
  };
  updateQuoteDraft: (patch: Partial<Omit<QuoteDraft, "lines">>) => void;
  addQuoteLine: (line: SharedQuoteLine) => void;
  removeQuoteLine: (lineId: string) => void;
  saveQuoteDraft: () => SavedQuote | null;
  transitionQuoteStatus: (quoteId: string, nextStatus: QuoteStatus) => SavedQuote | null;
  createWorkOrder: (input: {
    quoteNumber: string;
    customer: string;
    area: string;
    responsible: string;
    proof: string;
    dueDate: string;
    requiresInstallation: boolean;
    notes: string;
    stages: string[];
    totalLabel: string;
  }) => StoredWorkOrder | null;
  transitionWorkOrderStatus: (
    workOrderId: string,
    nextStatus: WorkOrderStatus,
  ) => StoredWorkOrder | null;
  createPurchase: (input: {
    supplier: string;
    eta: string;
    sourceReference: string;
    lines: StoredPurchaseLine[];
    autoSubmit?: boolean;
  }) => StoredPurchase | null;
  transitionPurchaseStatus: (
    purchaseId: string,
    nextStatus: PurchaseStatus,
  ) => StoredPurchase | null;
  addInventoryMovement: (input: Omit<StoredInventoryMovement, "id" | "createdAt">) => StoredInventoryMovement;
  removeInventoryMovement: (id: string) => void;
};

type PersistedState = {
  quoteDraft: QuoteDraft;
  savedQuotes: SavedQuote[];
  workOrders: StoredWorkOrder[];
  purchases: StoredPurchase[];
  inventoryMovements: StoredInventoryMovement[];
};

const STORAGE_KEY = "imprenta-shared-state-v2";

const initialQuoteDraft: QuoteDraft = {
  customer: customerRecords[0].businessName,
  validityDays: "7",
  deliveryWindow: "5 dias habiles",
  note: "Cotizacion referencial sujeta a confirmacion de stock y aprobacion tecnica.",
  includeVat: true,
  lines: [],
};

function parseManagedStock(stockLabel: string) {
  const digits = stockLabel.replace(/[^\d]/g, "");

  if (!digits) {
    return null;
  }

  const parsed = Number(digits);
  return Number.isFinite(parsed) ? parsed : null;
}

function getCatalogItemContext(line: SharedQuoteLine) {
  return catalogRecords.find(
    (record) => record.code === line.code || record.name === line.name,
  );
}

function inferSuggestedSupplier(line: SharedQuoteLine) {
  const catalogItem = getCatalogItemContext(line);
  const haystack = `${line.name} ${line.type} ${catalogItem?.category ?? ""}`.toLowerCase();

  if (
    haystack.includes("nova") ||
    haystack.includes("aseo") ||
    haystack.includes("sabanilla")
  ) {
    return (
      supplierRecords.find((record) => record.name === "Nova Industrial Chile")?.name ??
      supplierRecords[0].name
    );
  }

  if (
    haystack.includes("pvc") ||
    haystack.includes("letrero") ||
    haystack.includes("senaletica") ||
    haystack.includes("trovisel")
  ) {
    return (
      supplierRecords.find((record) => record.name === "PVC y Senaletica SPA")?.name ??
      supplierRecords[0].name
    );
  }

  return (
    supplierRecords.find((record) => record.name === "Papeles Bio Bio")?.name ??
    supplierRecords[0].name
  );
}

function estimateSuggestedUnitCost(line: SharedQuoteLine) {
  const catalogItem = getCatalogItemContext(line);
  const basePrice = catalogItem ? parseClp(catalogItem.price) : line.unitPrice;
  return Math.max(0, Math.round(basePrice * 0.72));
}

export function buildPurchaseSuggestionsFromQuoteLines(lines: SharedQuoteLine[]) {
  return lines.flatMap<PurchaseSuggestion>((line) => {
    const availableStock = parseManagedStock(line.stock);

    if (availableStock === null || line.quantity <= availableStock) {
      return [];
    }

    const shortageQuantity = line.quantity - availableStock;

    return [
      {
        id: `${line.id}-purchase`,
        item: line.name,
        sourceCode: line.code,
        sourceLineId: line.id,
        requiredQuantity: line.quantity,
        availableStock,
        shortageQuantity,
        suggestedSupplier: inferSuggestedSupplier(line),
        unitCost: estimateSuggestedUnitCost(line),
        reason: `Reposicion para cubrir faltante de ${line.name}`,
      },
    ];
  });
}

export function buildPurchaseLinesFromSuggestions(
  suggestions: PurchaseSuggestion[],
): StoredPurchaseLine[] {
  return suggestions.map((suggestion) => ({
    id: generateId("purchase-line"),
    item: suggestion.item,
    quantity: suggestion.shortageQuantity,
    unitCost: suggestion.unitCost,
    purpose: suggestion.reason,
  }));
}

function generateId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function computeQuoteTotals(draft: QuoteDraft) {
  const subtotal = draft.lines.reduce((sum, line) => {
    const gross = line.quantity * line.unitPrice;
    const discount = gross * (line.discountPercent / 100);
    return sum + (gross - discount);
  }, 0);

  const tax = draft.includeVat ? Math.round(subtotal * 0.19) : 0;
  const total = subtotal + tax;
  const hasProductionWork = draft.lines.some(
    (line) => line.type === "Servicio" || line.type === "Trabajo",
  );
  const requiresPurchaseReview = draft.lines.some((line) => {
    const stock = Number(line.stock.replace(/[^\d]/g, ""));
    return Number.isFinite(stock) && stock > 0 && line.quantity > stock;
  });

  return {
    subtotal,
    tax,
    total,
    hasProductionWork,
    requiresPurchaseReview,
  };
}

const AppStateContext = createContext<AppStateContextValue | null>(null);

function normalizeQuoteDraft(rawDraft: Partial<QuoteDraft> | undefined): QuoteDraft {
  return {
    ...initialQuoteDraft,
    ...rawDraft,
    lines: Array.isArray(rawDraft?.lines) ? rawDraft.lines : [],
  };
}

function normalizeSavedQuote(rawQuote: Partial<SavedQuote>): SavedQuote {
  return {
    ...(rawQuote as SavedQuote),
    status: normalizeQuoteStatus(rawQuote.status),
    lines: Array.isArray(rawQuote.lines) ? rawQuote.lines : [],
  };
}

function normalizeWorkOrder(rawWorkOrder: Partial<StoredWorkOrder>): StoredWorkOrder {
  return {
    ...(rawWorkOrder as StoredWorkOrder),
    status: normalizeWorkOrderStatus(rawWorkOrder.status),
    lines: Array.isArray(rawWorkOrder.lines) ? rawWorkOrder.lines : [],
    purchaseSuggestions: Array.isArray(rawWorkOrder.purchaseSuggestions)
      ? rawWorkOrder.purchaseSuggestions
      : [],
    stockReserved: Boolean(rawWorkOrder.stockReserved),
    stockConsumed: Boolean(rawWorkOrder.stockConsumed),
  };
}

function normalizePurchase(rawPurchase: Partial<StoredPurchase>): StoredPurchase {
  return {
    ...(rawPurchase as StoredPurchase),
    status: normalizePurchaseStatus(rawPurchase.status),
    lines: Array.isArray(rawPurchase.lines) ? rawPurchase.lines : [],
  };
}

function loadPersistedState(): PersistedState | null {
  if (typeof window === "undefined") {
    return null;
  }

  const keys = [STORAGE_KEY, "imprenta-shared-state-v1"];

  for (const key of keys) {
    try {
      const rawState = window.localStorage.getItem(key);
      if (!rawState) {
        continue;
      }

      const parsedState = JSON.parse(rawState) as Partial<PersistedState>;
      return {
        quoteDraft: normalizeQuoteDraft(parsedState.quoteDraft),
        savedQuotes: Array.isArray(parsedState.savedQuotes)
          ? parsedState.savedQuotes.map((quote) => normalizeSavedQuote(quote))
          : [],
        workOrders: Array.isArray(parsedState.workOrders)
          ? parsedState.workOrders.map((order) => normalizeWorkOrder(order))
          : [],
        purchases: Array.isArray(parsedState.purchases)
          ? parsedState.purchases.map((purchase) => normalizePurchase(purchase))
          : [],
        inventoryMovements: parsedState.inventoryMovements ?? [],
      };
    } catch {
      continue;
    }
  }

  return null;
}

export function AppStateProvider({ children }: { children: ReactNode }) {
  const [quoteDraft, setQuoteDraft] = useState<QuoteDraft>(initialQuoteDraft);
  const [savedQuotes, setSavedQuotes] = useState<SavedQuote[]>([]);
  const [workOrders, setWorkOrders] = useState<StoredWorkOrder[]>([]);
  const [purchases, setPurchases] = useState<StoredPurchase[]>([]);
  const [inventoryMovements, setInventoryMovements] = useState<StoredInventoryMovement[]>([]);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const frame = window.requestAnimationFrame(() => {
      const persisted = loadPersistedState();
      if (persisted) {
        setQuoteDraft(persisted.quoteDraft);
        setSavedQuotes(persisted.savedQuotes);
        setWorkOrders(persisted.workOrders);
        setPurchases(persisted.purchases);
        setInventoryMovements(persisted.inventoryMovements);
      }
      setHydrated(true);
    });

    return () => window.cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    if (!hydrated) {
      return;
    }

    const persistedState: PersistedState = {
      quoteDraft,
      savedQuotes,
      workOrders,
      purchases,
      inventoryMovements,
    };

    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(persistedState));
  }, [hydrated, inventoryMovements, purchases, quoteDraft, savedQuotes, workOrders]);

  const quoteDraftTotals = useMemo(() => computeQuoteTotals(quoteDraft), [quoteDraft]);

  const liveStats = useMemo(
    () => ({
      quotes: savedQuotes.length,
      workOrders: workOrders.length,
      purchases: purchases.length,
      inventoryMovements: inventoryMovements.length,
      quoteValue: savedQuotes.reduce((sum, quote) => sum + quote.total, 0),
      purchaseValue: purchases.reduce((sum, purchase) => sum + purchase.total, 0),
      approvedQuotes: savedQuotes.filter((quote) => quote.status === "Aprobada").length,
      openPurchases: purchases.filter(
        (purchase) => purchase.status !== "Recibida" && purchase.status !== "Cancelada",
      ).length,
    }),
    [inventoryMovements.length, purchases, savedQuotes, workOrders.length],
  );

  function appendHandoffMovements(movements: HandoffMovementInput[]) {
    if (movements.length === 0) {
      return;
    }

    setInventoryMovements((current) => {
      const existingSignatures = new Set(
        current.map((movement) =>
          movementSignature({
            item: movement.item,
            operation: movement.operation,
            quantity: movement.quantity,
            reference: movement.reference,
          }),
        ),
      );

      const freshMovements = movements
        .filter((movement) => !existingSignatures.has(movementSignature(movement)))
        .map<StoredInventoryMovement>((movement) => ({
          ...movement,
          id: generateId("movement"),
          createdAt: new Date().toISOString(),
          autoGenerated: true,
        }));

      return freshMovements.length > 0 ? [...freshMovements, ...current] : current;
    });
  }

  function updateQuoteDraft(patch: Partial<Omit<QuoteDraft, "lines">>) {
    setQuoteDraft((current) => ({ ...current, ...patch }));
  }

  function addQuoteLine(line: SharedQuoteLine) {
    setQuoteDraft((current) => ({
      ...current,
      lines: [...current.lines, line],
    }));
  }

  function removeQuoteLine(lineId: string) {
    setQuoteDraft((current) => ({
      ...current,
      lines: current.lines.filter((line) => line.id !== lineId),
    }));
  }

  function saveQuoteDraft() {
    if (quoteDraft.lines.length === 0) {
      return null;
    }

    const customer =
      customerRecords.find((record) => record.businessName === quoteDraft.customer) ??
      customerRecords[0];
    const totals = computeQuoteTotals(quoteDraft);
    const quoteNumber = `COT-LOCAL-${String(savedQuotes.length + 1).padStart(3, "0")}`;

    const validUntilDate = new Date();
    validUntilDate.setDate(validUntilDate.getDate() + Number(quoteDraft.validityDays || "0"));

    const savedQuote: SavedQuote = {
      id: generateId("quote"),
      number: quoteNumber,
      customer: customer.businessName,
      rut: customer.rut,
      commune: customer.commune,
      paymentTerms: customer.paymentTerms,
      validUntilLabel: validUntilDate.toLocaleDateString("es-CL"),
      deliveryWindow: quoteDraft.deliveryWindow,
      note: quoteDraft.note,
      includeVat: quoteDraft.includeVat,
      subtotal: totals.subtotal,
      tax: totals.tax,
      total: totals.total,
      lines: quoteDraft.lines.map((line) => ({ ...line })),
      status: "Borrador",
      createdAt: new Date().toISOString(),
    };

    setSavedQuotes((current) => [savedQuote, ...current]);
    return savedQuote;
  }

  function transitionQuoteStatus(quoteId: string, nextStatus: QuoteStatus) {
    let updatedQuote: SavedQuote | null = null;

    setSavedQuotes((current) =>
      current.map((quote) => {
        if (quote.id !== quoteId || !canTransitionQuote(quote.status, nextStatus)) {
          return quote;
        }

        updatedQuote = { ...quote, status: nextStatus };
        return updatedQuote;
      }),
    );

    return updatedQuote;
  }

  function createWorkOrder(input: {
    quoteNumber: string;
    customer: string;
    area: string;
    responsible: string;
    proof: string;
    dueDate: string;
    requiresInstallation: boolean;
    notes: string;
    stages: string[];
    totalLabel: string;
  }) {
    const sourceQuote = savedQuotes.find((quote) => quote.number === input.quoteNumber);

    if (sourceQuote && sourceQuote.status !== "Aprobada") {
      return null;
    }

    const existingWorkOrder = workOrders.find((order) => order.quoteNumber === input.quoteNumber);
    if (existingWorkOrder) {
      return existingWorkOrder;
    }

    const inheritedLines = sourceQuote?.lines.map((line) => ({ ...line })) ?? [];
    const purchaseSuggestions = buildPurchaseSuggestionsFromQuoteLines(inheritedLines);
    const workOrderNumber = `OT-LOCAL-${String(workOrders.length + 1).padStart(3, "0")}`;

    let linkedPurchaseNumber: string | undefined;

    if (purchaseSuggestions.length > 0) {
      const [primarySuggestion] = purchaseSuggestions;
      const purchaseLines = buildPurchaseLinesFromSuggestions(purchaseSuggestions);
      const subtotal = purchaseLines.reduce(
        (sum, line) => sum + line.quantity * line.unitCost,
        0,
      );
      const vat = Math.round(subtotal * 0.19);
      linkedPurchaseNumber = `OC-LOCAL-${String(purchases.length + 1).padStart(3, "0")}`;
      const autoPurchase: StoredPurchase = {
        id: generateId("purchase"),
        number: linkedPurchaseNumber,
        supplier: primarySuggestion.suggestedSupplier,
        eta: input.dueDate,
        status: "Pendiente aprobacion",
        lines: purchaseLines,
        subtotal,
        vat,
        total: subtotal + vat,
        createdAt: new Date().toISOString(),
        sourceReference: workOrderNumber,
      };

      setPurchases((current) => [autoPurchase, ...current]);
    }

    const workOrder: StoredWorkOrder = {
      id: generateId("wo"),
      number: workOrderNumber,
      quoteNumber: input.quoteNumber,
      customer: input.customer,
      area: input.area,
      responsible: input.responsible,
      proof: input.proof,
      dueDate: input.dueDate,
      requiresInstallation: input.requiresInstallation,
      notes: input.notes,
      stages: input.stages,
      status: "Pendiente",
      totalLabel: input.totalLabel,
      lines: inheritedLines,
      purchaseSuggestions: purchaseSuggestions.map((suggestion) => ({ ...suggestion })),
      createdAt: new Date().toISOString(),
      stockReserved: inheritedLines.length > 0,
      purchaseNumber: linkedPurchaseNumber,
    };

    setWorkOrders((current) => [workOrder, ...current]);

    if (sourceQuote) {
      setSavedQuotes((current) =>
        current.map((quote) =>
          quote.number === input.quoteNumber
            ? { ...quote, status: "Convertida", workOrderNumber: workOrder.number }
            : quote,
        ),
      );
    }

    appendHandoffMovements(buildReservationMovements(inheritedLines, workOrder.number));

    return workOrder;
  }

  function transitionWorkOrderStatus(workOrderId: string, nextStatus: WorkOrderStatus) {
    const sourceOrder = workOrders.find((order) => order.id === workOrderId);

    if (!sourceOrder || !canTransitionWorkOrder(sourceOrder.status, nextStatus)) {
      return null;
    }

    if (nextStatus === "En produccion" && !sourceOrder.stockConsumed) {
      appendHandoffMovements(
        buildConsumptionMovements(sourceOrder.lines, sourceOrder.number),
      );
    }

    let updatedOrder: StoredWorkOrder | null = null;

    setWorkOrders((current) =>
      current.map((order) => {
        if (order.id !== workOrderId) {
          return order;
        }

        updatedOrder = {
          ...order,
          status: nextStatus,
          stockConsumed:
            nextStatus === "En produccion" ? true : order.stockConsumed,
        };
        return updatedOrder;
      }),
    );

    return updatedOrder;
  }

  function createPurchase(input: {
    supplier: string;
    eta: string;
    sourceReference: string;
    lines: StoredPurchaseLine[];
    autoSubmit?: boolean;
  }) {
    if (input.lines.length === 0) {
      return null;
    }

    const subtotal = input.lines.reduce(
      (sum, line) => sum + line.quantity * line.unitCost,
      0,
    );
    const vat = Math.round(subtotal * 0.19);
    const purchase: StoredPurchase = {
      id: generateId("purchase"),
      number: `OC-LOCAL-${String(purchases.length + 1).padStart(3, "0")}`,
      supplier: input.supplier,
      eta: input.eta,
      status: input.autoSubmit ? "Pendiente aprobacion" : "Borrador",
      lines: input.lines,
      subtotal,
      vat,
      total: subtotal + vat,
      createdAt: new Date().toISOString(),
      sourceReference: input.sourceReference,
    };

    setPurchases((current) => [purchase, ...current]);
    return purchase;
  }

  function transitionPurchaseStatus(purchaseId: string, nextStatus: PurchaseStatus) {
    const sourcePurchase = purchases.find((purchase) => purchase.id === purchaseId);

    if (!sourcePurchase || !canTransitionPurchase(sourcePurchase.status, nextStatus)) {
      return null;
    }

    if (nextStatus === "Recibida") {
      appendHandoffMovements(
        buildReceiptMovements(sourcePurchase.lines, sourcePurchase.number),
      );
    }

    let updatedPurchase: StoredPurchase | null = null;

    setPurchases((current) =>
      current.map((purchase) => {
        if (purchase.id !== purchaseId) {
          return purchase;
        }

        updatedPurchase = {
          ...purchase,
          status: nextStatus,
          receivedAt: nextStatus === "Recibida" ? new Date().toISOString() : purchase.receivedAt,
        };
        return updatedPurchase;
      }),
    );

    return updatedPurchase;
  }

  function addInventoryMovement(input: Omit<StoredInventoryMovement, "id" | "createdAt">) {
    const movement: StoredInventoryMovement = {
      ...input,
      id: generateId("movement"),
      createdAt: new Date().toISOString(),
      autoGenerated: false,
    };

    setInventoryMovements((current) => [movement, ...current]);
    return movement;
  }

  function removeInventoryMovement(id: string) {
    setInventoryMovements((current) => current.filter((movement) => movement.id !== id));
  }

  const value: AppStateContextValue = {
    quoteDraft,
    savedQuotes,
    workOrders,
    purchases,
    inventoryMovements,
    quoteDraftTotals,
    liveStats,
    updateQuoteDraft,
    addQuoteLine,
    removeQuoteLine,
    saveQuoteDraft,
    transitionQuoteStatus,
    createWorkOrder,
    transitionWorkOrderStatus,
    createPurchase,
    transitionPurchaseStatus,
    addInventoryMovement,
    removeInventoryMovement,
  };

  return <AppStateContext.Provider value={value}>{children}</AppStateContext.Provider>;
}

export function useAppState() {
  const context = useContext(AppStateContext);

  if (!context) {
    throw new Error("useAppState must be used inside AppStateProvider");
  }

  return context;
}

export function formatStoredQuoteTotal(total: number) {
  return formatClp(total);
}
